package com.aim.dnaautomation.helpers.dataproviders;

import org.testng.annotations.DataProvider;

import java.util.Arrays;

import static com.aim.dnaautomation.helpers.configwrapperconstant.ConfigWrapperConstants.*;
import static com.aim.dnaautomation.helpers.rabbitmqconstants.Constants.*;


public class DataProviders {

    @DataProvider(name = "sendAttachmentsToDNAProcessor")
    public Object[][] sendAttachmentsToDNAProcessor() {

        return new Object[][]{
                {Arrays.asList(ATTACHMENTID1_FOR_CASEID1, ATTACHMENTID2_FOR_CASEID1), CASEID_1}
                , {Arrays.asList(ATTACHMENTID1_FOR_CASEID2, ATTACHMENTID2_FOR_CASEID2), CASEID_2}
                , {Arrays.asList(ATTACHMENTID1_FOR_CASEID3), CASEID_3}
                , {Arrays.asList(ATTACHMENTID1_FOR_CASEID4, ATTACHMENTID2_FOR_CASEID4, ATTACHMENTID3_FOR_CASEID4), CASEID_4}
        };
    }

    @DataProvider(name = "RBMCaseSavedEventsPROD")
    public Object[][] RBMCaseSavedEventsPROD() {

        return new Object[][]{
                {CERVICAL_MRI_CPT_CODE_3, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_TRUE},
                {CT_ABDOMEN_AND_OR_PELVIS_AIM_CPT_CODE, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_TRUE},
                {CHEST_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_45,HOUSEACCOUNT_TRUE},
                {SINUSITIS_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_201,HOUSEACCOUNT_TRUE},
                {CT_ABDOMEN_AND_OR_PELVIS_AIM_CPT_CODE, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE},
                {CHEST_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_45,HOUSEACCOUNT_FALSE}
                , {SINUSITIS_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_201,HOUSEACCOUNT_FALSE}
                , {CERVICAL_MRI_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {CHEST_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {CHEST_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {LUMBAR_MRI_CPT_CODE_3, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {CERVICAL_MRI_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE}
                , {CERVICAL_MRI_CPT_CODE_3, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE}

        };
    }

    @DataProvider(name = "RBMCaseSavedEvent")
    public Object[][] RBMCaseSavedEvent() {

        return new Object[][]{
                {BREAST_MRI_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE}
                , {BREAST_MRI_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE}
                , {SINUSITIS_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE}
                , {SINUSITIS_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE}
                , {DIVERTICULITIS_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {DIVERTICULITIS_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE}
                , {CHEST_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE}
                , {CHEST_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE}


        };
    }

    @DataProvider(name = "MSKCaseSavedEventsPROD")
    public Object[][] MSKCaseSavedEventsPROD() {

        return new Object[][]{
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE},

                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_45,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_201,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_218,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_227,HOUSEACCOUNT_FALSE},};
    }

    @DataProvider(name = "MSKCaseSavedEvents")
    public Object[][] MSKCaseSavedEvents() {

        return new Object[][]{
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_45,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_201,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_218,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_SAVE_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_227,HOUSEACCOUNT_FALSE},};
    }

    @DataProvider(name = "MSKCasePromotedEvents")
    public Object[][] MSKCasePromotedEvents() {

        return new Object[][]{
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_85,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_40,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_45,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_55,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_201,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_218,HOUSEACCOUNT_FALSE},
                {MSK_NON_CONFIGURED_CPT, MSK_PRODUCT_ID, MSK_CASE_PROMOTED_EVENT_TYPE_CD,
                        MSK_PUBLISHER_APPLICATION_ID, MSK_PUBLISHER_EVENT_ID, MSK_PRODUCT_NAME, MSK_DATE_OF_BIRTH, CLIENT_ID_227,HOUSEACCOUNT_FALSE},};
    }

    @DataProvider(name = "SurgicalCaseSavedEvents")
    public Object[][] SurgicalCaseSavedEvents() {

        return new Object[][]{
                {CERVICAL_MRI_CPT_CODE_1, PRODUCT_ID_SURG, EVENT_TYPE_CD_SURG,
                        PUBLISHER_APPLICATION_ID_SURG, PUBLISHER_EVENT_ID_SURG, PRODUCT_NAME_SURG, DATE_OF_BIRTH_SURG, CLIENT_ID_55,HOUSEACCOUNT_FALSE},
        };
    }

    @DataProvider(name = "CardiologyCaseSavedEvents")
    public Object[][] CardiologyCaseSavedEvents() {

        return new Object[][]{
                {CARDIOLOGY_CPT_CODE_4, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE},
                {CARDIOLOGY_CPT_CODE_2, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE},
                {CARDIOLOGY_CPT_CODE_3, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE},
                {CARDIOLOGY_CPT_CODE_1, PRODUCT_ID, EVENT_TYPE_CD,
                        PUBLISHER_APPLICATION_ID, PUBLISHER_EVENT_ID, PRODUCT_NAME, DATE_OF_BIRTH, CLIENT_ID_183,HOUSEACCOUNT_FALSE},};
    }

    // InitiatePortalAppeals
    // For Parent Sol = 12
    //Combination1
    @DataProvider(name = "InitiatePortalEnabledAppeals_12_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED")
    public Object[][] InitiatePortalEnabledAppeals_12_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED() {
        return new Object[][]{
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //5
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //6
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //7
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //8
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //9
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //10
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //11
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //12
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //13
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //14
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //15
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //16
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //17
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //18
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //19
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //20
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //21
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //22
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //23
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //24
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //25
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},


        };
    }

    // For Parent Sol = 14
    //Combination1
    @DataProvider(name = "InitiatePortalEnabledAppeals_14_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED")
    public Object[][] InitiatePortalEnabledAppeals_14_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED() {
        return new Object[][]{
                //26
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_0},

                //27
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //28
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_17, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //29
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //30
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_0},

        };
    }

    // For Parent Sol = null
    //Combination1
    @DataProvider(name = "InitiatePortalEnabledAppeals_Null_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED")
    public Object[][] InitiatePortalEnabledAppeals_Null_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED() {
        return new Object[][]{

                //31
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, null, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //32
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_3, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, null, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //33
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_6, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //34
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_7, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //35
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_8, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //36
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_9, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                //37
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_11, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

        };
    }

    @DataProvider(name = "InitiateMultiplePortalEnabledAppeals_14_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED")
    public Object[][] InitiateMultiplePortalEnabledAppeals_14_23_55_HPR_COMMERCIAL_TX_NONAUTHORIZED_CLOSED() {
        return new Object[][]{
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_0},

                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

        };
    }


    @DataProvider(name = "portalAppealsNegativeValidation")
    public Object[][] portalAppealsNegativeValidation() {
        return new Object[][]{
                {PORTAL_APPEALS_PARENTSOLUTIONID_16, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_MEDICARE, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_OPEN, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_94, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_MEDICAID, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OUTCOME_NOT_APPROVED, PORTAL_APPEALS_CASESSTATUS_CLOSED, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_95, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE, PORTAL_APPEALS_PROGRAM_CODE_QI,
                        PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OUTCOME_NON_AUTHORIZED, PORTAL_APPEALS_CASESSTATUS_OPEN, PORTAL_APPEALS_ID, PORTAL_APPEALS_OUTCOMECODE_N, PORTAL_APPEALS_REASONCODE_75, PORTAL_APPEALS_SEQUENCE_NUMBER_1},

        };
    }

    //InitiatePortalOptions - Positive Scenarios
    @DataProvider(name = "PortalInitiateAppealsOptions_PositiveScenarios_Response1")
    public Object[][] PortalInitiateAppealsOptions_PositiveScenarios_Response1() {
        return new Object[][]{
                //1
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //2
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //3
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //4
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //5
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //6
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //7
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //8
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_17, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //9
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //10
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //11
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //12
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_3, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //13
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_6, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //14
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_7, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //15
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_8, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //16
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_9, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //17
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_11, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},


        };
    }

    @DataProvider(name = "PortalInitiateAppealsOptions_PositiveScenarios_Response2")
    public Object[][] PortalInitiateAppealsOptions_PositiveScenarios_Response2() {
        return new Object[][]{
                //1
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //2
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //3
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //4
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //5
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //6
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //7
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //8
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_17, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //9
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //10
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //11
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //12
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //13
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_17, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //14
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //15
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //16
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //17
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_3, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //18
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_6, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //19
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_7, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //20
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_8, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},

                //21
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_9, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},

                //22
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_11, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},


                //23
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //24
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_3, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //25
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_6, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //26
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_7, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //27
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_8, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //28
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_9, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},

                //29
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_11, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_AR},


        };
    }

    @DataProvider(name = "PortalInitiateAppealsOptions_PositiveScenarios_Response3")
    public Object[][] PortalInitiateAppealsOptions_PositiveScenarios_Response3() {
        return new Object[][]{

                //1
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},
                //2
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //3
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //4
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //5
                {PORTAL_APPEALS_PARENTSOLUTIONID_12, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},
                //6
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},
                //7
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //8
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_17, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //9
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_15, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //10
                {PORTAL_APPEALS_PARENTSOLUTIONID_14, PORTAL_APPEALS_SOLUTIONID_16, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //11
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_1, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //12
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_3, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //13
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_6, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //14
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_7, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_MT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //15
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_8, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //16
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_9, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_SP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_TX, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},

                //17
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_11, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_NULL},


        };
    }

    //InitiatePortalOptions - Negative Scenarios
    @DataProvider(name = "PortalInitiateAppealsOptions_NegativeScenarios")
    public Object[][] PortalInitiateAppealsOptions_NegativeSceanrios() {
        return new Object[][]{

                //1
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_AT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //2
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_160, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_IL, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //3
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_25, PORTAL_APPEALS_CLIENTID_218, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_OK, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //4
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_219, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_AT, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_SP},
                //5
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_24, PORTAL_APPEALS_CLIENTID_220, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_NM, PORTAL_APPEALS_OPTION_APPEALTYPE_PROVIDER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_OP},
                //6
                {PORTAL_APPEALS_PARENTSOLUTIONID_15, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_HPR, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_AT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},

                //7
                {PORTAL_APPEALS_PARENTSOLUTIONID_NULL, PORTAL_APPEALS_SOLUTIONID_23, PORTAL_APPEALS_CLIENTID_55, PORTAL_APPEALS_USERROLECODE_OP, PORTAL_APPEALS_FUNDING_TYPE_NULL,
                        PORTAL_APPEALS_PROGRAM_CODE_NULL, PORTAL_APPEALS_LINEOFBUSINESSCODE_COMMERCIAL, PORTAL_APPEALS_ISSUANCESTATECODE_AT, PORTAL_APPEALS_OPTION_APPEALTYPE_MEMBER,
                        PORTAL_APPEALS_OPTION_APPEALREQUESTEDBY_MEMBER},
        };
    }

}
